title:  7bits
tagline:  О работе и жизни компании

disqus:
  comments: true
  disqus_shortname: 'sevenbits'

analytics:
  yandex:
    id: 45958344
  google:
    id:

google-ID:

menu:

social:
- {icon: 'globe', link: 'https://7bits.it'}
- {icon: 'vk', link: 'https://vk.com/7bits'}
- {icon: 'linkedin', link: 'https://www.linkedin.com/company/2559736/'}
- {icon: 'envelope', link: 'mailto:aloha@7bits.it'}
